### ISSUE TITLE
Using placeholders in effects doesnt not work

### ISSUE THREAD

**Issue by Sedri05** [Auxilor/libreforge#23]
**Describe the bug**
When putting a placeholder (for example %player_y%) in (for example the mutliplier arg) any effect arg it does not work and just ignores it.

**To Reproduce**
Use this effect:
```
    - id: damage_multiplier
      args:
        multiplier: 1+(%player_y%/100)
      triggers:
      - melee_attack
```

**Expected behavior**
Should do some magic and calculate damage with placeholder in mind

**Additional context**
While ur here might as well look at the suggestion i did a while back ;)
Suggestion: https://github.com/Auxilor/libreforge/issues/17
