### ISSUE TITLE
Conditions to limit item use dont work 

### ISSUE THREAD

**Issue by OmegaWulf** [Auxilor/libreforge#40]
**Describe the bug**
Placing a condition on an EcoItem does nothing. 

**To Reproduce**
1. Set a condition on an EcoItem pickaxe like so: 
```
      effects: []
      conditions: 
        - id: has_skill_level
          args:
            skill: mining
            level: 15
      lore:
        - ""
```
2. Have default EcoSkills names & setup. 
3. Have lower than 15 mining. 
4. Equip the pickaxe and use it normally. 

**Expected behavior**
I expect the player to ONLY be able to use the pickaxe when the conditions return a value of TRUE. 

**Server Information (please complete the following information):**
- Paper 1.18.2
- Latest Eco
