### ISSUE TITLE
give_points effect doesn't support kill_boss

### ISSUE THREAD

**Issue by grzybeek** [Auxilor/libreforge#41]
**Describe the bug**
![image](https://user-images.githubusercontent.com/40837847/176774981-6519d1f7-1425-4f2c-bdfc-995dd1673211.png)

**To Reproduce**
I've edited EcoBosses config and added
```
- id: give_points
  args: 
    type: g_golemkills
    amount: 1
  triggers:
    - kill_boss
```

**Expected behavior**
Give points for killing boss

**Screenshots**

**Server Information (please complete the following information):**
- Version: (output of `/ver` command): This server is running Paper version git-Paper-386 (MC: 1.18.2) (Implementing API version 1.18.2-R0.1-SNAPSHOT) (Git: 072f54c on ver/1.18.2)
- Version of plugin and eco: eco 6.37, ecobosses 8.50

**Additional context**
iirc `spawn_boss` trigger didn't work too
