### ISSUE TITLE
Create a condition for an item

### ISSUE THREAD

**Issue by OmegaWulf** [Auxilor/libreforge#42]
**Describe the solution you'd like**
I'd like the ability to add a `condition` to an item which will prevent use of the item unless the condition is true. 

For example, a pickaxe with a mining level requirement to use. Or armor that requires a defense level to equip. 

Something that would look like this: 
```
      effects: []
      conditions: 
        - id: has_skill_level
          args:
            skill: mining
            level: 15
      lore:
        - ""
```
