### ISSUE TITLE
cancel_event doesn't work for send_message trigger

### ISSUE THREAD

**Issue by MillionthOdin16** [Auxilor/libreforge#59]
**Describe the bug**
Effect `cancel_event` doesn't currently work for the `send_message` trigger. With this config I would expect it to cancel/hide the 'hurt me' message in chat.

```
effects:
  - id: run_chain_inline
    args:
      every: 1
      chain:
        effects:
          - id: cancel_event
          - id: run_command
            args:
              command: "lightning %player_name%"
    triggers:
      - send_message
    filters:
     text_contains: 
       - "hurt me"
```

**Server Information (please complete the following information):**
- Version: git-Paper-177 (MC: 1.19.2)
- eco version 6.42.0
